AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  InputBucketName:
    Type: String
    Default: quote-json-data
Resources:
  DDBtable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Ref: InputBucketName
  InputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: InputBucketName
  ImportJsonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://quoteapp-artifacts-sam/12af83fce7c01e41d6ef90e71f81e96f
      Handler: app.handler
      Runtime: nodejs16.x
      Timeout: 60
      Environment:
        Variables:
          DDBtable:
            Ref: DDBtable
      Policies:
      - AWSLambdaExecute
      - DynamoDBCrudPolicy:
          TableName:
            Ref: InputBucketName
      - S3CrudPolicy:
          BucketName:
            Ref: InputBucketName
      Events:
        ImportJsonFunctionEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: InputS3Bucket
            Events: s3:ObjectCreated:*
  QuoteApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs16.x
      Handler: index.handler
      Environment:
        Variables:
          TABLE_NAME:
            Ref: InputBucketName
      Policies: AmazonDynamoDBFullAccess
      CodeUri: s3://quoteapp-artifacts-sam/f6025b38bb4c00aedeeb46f994a4e034
      Events:
        MyApiResource:
          Type: Api
          Properties:
            Path: /quotes
            Method: get
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for quote function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/quotes/
  QuoteApiFunction:
    Description: QuoteApiFunction ARN
    Value:
      Fn::GetAtt:
      - QuoteApiFunction
      - Arn
  QuoteApiFunctionIamRole:
    Description: Implicit IAM Role created for QuoteApiFunction
    Value:
      Fn::GetAtt:
      - QuoteApiFunction
      - Arn
