AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  InputBucketName:
    Type: String
    Default: 'quote-json-data'
Resources:
  DDBtable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref InputBucketName
  InputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName
  ImportJsonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: importFunction/
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 60
      Environment:
        Variables:
          DDBtable: !Ref DDBtable
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref InputBucketName        
        - S3CrudPolicy:
            BucketName: !Ref InputBucketName
      Events:
        ImportJsonFunctionEvent:
          Type: S3
          Properties:
            Bucket: !Ref InputS3Bucket
            Events: s3:ObjectCreated:*